version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - artemrys
  assignees:
  - artemrys
  ignore:
  - dependency-name: pytest
    versions:
    - 6.2.1
