language: python
python:
  - 3.7
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r test-requirements.txt
script: pytest
after_success:
  - codecov