swagger: '2.0'
info:
  title: Smokerino Backend Gateway
  description: Smokerino Backend Gateway
  version: 1.0.0
host: smokerino-backend-hnxafqqzca-uc.a.run.app
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/cigarette:
    post:
      summary: Adds smoked cigarette for a given user
      operationId: add_cigarette
      x-google-backend:
        address: https://us-central1-smokerino-backend.cloudfunctions.net/add-cigarette
      responses:
        '200':
          description: Successful response
          schema:
            type: string
        '405':
          description: Method not allowed
          schema:
            type: string
      security:
        - api_key: []

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
